### ISSUE TITLE
Won't load projects

### ISSUE THREAD

**Issue by mulhoon** [MoralAlberto/vercelios-issues#1]
Hi, your app looks really interesting but my iPhone 13 Pro, iOS 17.5.1 won't load any projects after I give it access to all. my personal Vercel projects. Any ideas?

**Comment by MoralAlberto** [comment]
Hello, Thank you for reaching out to me. Let's try to figure out what is happening. 

Do you have multiple Vercel teams? I mean, in my case only one of them has projects (the first one), if I select the other one is completely empty

<img src="https://github.com/MoralAlberto/vercelios-issues/assets/931211/d6c3b1d8-7f18-45cf-95a4-6c5d2598d2ba" width="300">
