### ISSUE TITLE
I recently subscribed to your service, but I made this subscription by mistake. I would like to request a refund for the amount of 19.99 EUR charged to my account.  Please let me know if you need any additional information from my side to process this refund. I appreciate your understanding and prompt assistance in this matter.  Thank you,

### ISSUE THREAD

**Issue by fediralydev** [MoralAlberto/vercelios-issues#2]
## Title
[Brief Title Reflecting the Issue or Suggestion]

## Feedback Type
(Please select one)
- [ ] Bug
- [ ] Feature Request

## Description
Provide a detailed description of the issue you encountered or the feature you would like to see implemented. Please be as clear and concise as possible.

## Steps to Reproduce
(If reporting a bug)
1. Navigate to '...'
2. Click on '...'
3. Scroll to '...'
4. Observed error

## Expected Outcome
Describe what you expected to happen if reporting a bug, or how you envision the feature working if making a suggestion.

## Environment
(If reporting a bug)
- Device: [e.g., iPhone 12, Desktop PC]
- OS: [e.g., iOS 14, Windows 10]
- Browser: [e.g., Firefox, Safari]
- Version: [e.g., 78]

## Additional Information
Include any other context or screenshots that would aid in resolving the issue or understanding the feature request.

**Comment by MoralAlberto** [comment]
Hello, I can't issue a refund (only Apple can do that), but please follow these steps: https://support.apple.com/en-us/118223

**Comment by fediralydev** [comment]
bro i need help apple not get me back money  and its was all this by mistake so now i need  back my money
![Screenshot 2024-06-30 at 10 46 13 PM](https://github.com/MoralAlberto/vercelios-issues/assets/109765255/20f762d2-8bcb-4369-ba0f-8db2b23f2ae2)

**Comment by fediralydev** [comment]
Bro, i This was a mistake 'cause I only tried the 3-day free trial. It was all a mistake, bro. If you don't refund my money, we're gonna have a big problem.

**Comment by MoralAlberto** [comment]
Hello @federalydev, do you understand that I have no access to the tools required to refund your subscription? Apple does not provide these capabilities to developers. Please consider "Review Decision" or contact Apple Support (https://getsupport.apple.com)

**Comment by fediralydev** [comment]
I understand, but this problem is from you, not Apple. When people subscribe by mistake, it's your problem, bro. People can't get refunds, and it's all because of how your system is set up.
