### ISSUE TITLE
Cannot stop pro pop up

### ISSUE THREAD

**Issue by jasonheron** [MoralAlberto/vercelios-issues#5]
## title 
upgrade / pro pop up always showing with no close option

## Feedback Type
(Please select one)
- [ x ] Bug
- [ ] Feature Request

## Description
As soon as the app loads, the upgrade pop up shows and there's no way to close it without paying!

## Steps to Reproduce
(If reporting a bug)
1. Navigate to '...'
2. Click on '...'
3. Scroll to '...'
4. Observed error

## Expected Outcome
Remove the pop up?

## Environment
(If reporting a bug)
- Device: [e.g., iPhone 12, Desktop PC]
- OS: [e.g., iOS 14, Windows 10]
- Browser: [e.g., Firefox, Safari]
- Version: [e.g., 78]

## Additional Information
Include any other context or screenshots that would aid in resolving the issue or understanding the feature request.

**Comment by MoralAlberto** [comment]
Hello! Thank you for reaching out. This is the intended behavior. You can use Vercelios with a 3-day free trial
